<a href="https://colab.research.google.com/github/cuzmyk/data_mining/blob/main/pr1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическая работа №2. Библиотека Numpy

## Полезные материалы
- [Блокнот с полной теорией](https://colab.research.google.com/drive/1JlqwrIRsmnc9rW6Tj1XNgrtk--43dKvT?usp=sharing)
- [Блокнот с краткой теорией](https://colab.research.google.com/drive/1elIYEseXIidm5UUXnjgzWUehisw_OQ0w?usp=sharing)
- [Шпаргалка по numpy](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
- [Numpy quick start](https://docs.scipy.org/doc/numpy/user/quickstart.html)
- [Datacamp numpy tutorial](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

## **Блок №1. Базовый уровень**

Установите зависимость с библиотекой NumPy:

In [ ]:
# Ваш код
import numpy as np

### **Задание №1. Создание массивов:**

а) Создайте одномерный массив из 10 нулей:


In [ ]:
# Ваш код
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


б) Создайте двумерный массив с размерностью 5x5, заполненный единицами:

In [ ]:
# Ваш код
ones_array = np.ones((5, 5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


в) Создайте массив с размерностью 3x3x3 со случайными значениями:

In [ ]:
# Ваш код
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.05901339 0.6842541  0.92824984]
  [0.17609774 0.21404296 0.08487049]
  [0.37200418 0.23654868 0.35136898]]

 [[0.75511895 0.54526859 0.89975316]
  [0.31260151 0.87220257 0.53186955]
  [0.11736428 0.71925156 0.26216879]]

 [[0.55689193 0.32915601 0.07115853]
  [0.44859575 0.96235823 0.273023  ]
  [0.36797949 0.02088253 0.08223113]]]


### **Задание №2. Индексация и срезы:**

а) Извлеките второй элемент из созданного одномерного массива нулей:

In [ ]:
# Ваш код
second_el = zeros_array[1]
print(second_el)

0.0


б) Выберите вторую строку из двумерного массива единиц:

In [ ]:
# Ваш код
second_row = ones_array[1]
print(second_row)

[1. 1. 1. 1. 1.]


в) Получите первые два элемента каждой строки из двумерного массива единиц:

In [ ]:
# Ваш код
first_two_elements = ones_array[:, :2]
print(first_two_elements)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### **Задание №3. Операции над массивами:**

   а) Прибавьте 10 ко всем элементам одномерного массива нулей:


In [ ]:
# Ваш код
tens_array = zeros_array + 10
print(tens_array)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


   б) Умножьте каждый элемент двумерного массива единиц на 3:


In [ ]:
# Ваш код
threes_array = ones_array * 3
print(threes_array)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


   в) Вычислите сумму всех элементов в массиве 3x3x3 со случайными значениями:

In [ ]:
# Ваш код
total_sum = np.sum(random_array)
print(total_sum)

11.234325939336614


### **Задание №4. Использование функций и методов NumPy:**


   а) Найдите максимальное и минимальное значения в массиве 3x3x3:


In [ ]:
# Ваш код
max_value = np.max(random_array)
min_value = np.min(random_array)

print("Макс:", max_value)
print("Мин", min_value)

Макс: 0.9623582310599544
Мин 0.020882533283849924


   б) Вычислите среднее значение всех элементов в одномерном массиве нулей после добавления к ним числа 10:


In [ ]:
# Ваш код
mean_value = np.mean(tens_array)
print(mean_value)

10.0


   в) Используйте функцию `np.reshape` для изменения формы одномерного массива нулей в двумерный массив 2x5:

In [ ]:
# Ваш код
reshaped_array = np.reshape(zeros_array, (2, 5))
print(reshaped_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### **Задание №5. Логическая индексация:**

а) Создайте двумерный массив 4x4 со случайными целыми числами от 0 до 100. Затем выберите из этого массива все элементы, которые больше 70:

In [ ]:
# Ваш код
random_array = np.random.randint(0, 101, size=(4, 4))
required_elements = random_array[random_array > 70]

print("Двумерный массив 4x4 со случайными целыми числами:\n", random_array)
print("Элементы, которые больше 70:\n", required_elements)

Двумерный массив 4x4 со случайными целыми числами:
 [[76 87 66 57]
 [87 16 14 77]
 [68 52 83 24]
 [92 84 64 86]]
Элементы, которые больше 70:
 [76 87 87 77 83 92 84 86]


б) Значения элементов, которые меньше 50, замените на 0:

In [ ]:
# Ваш код
random_array[random_array < 50] = 0
print(random_array)

[[76 87 66 57]
 [87  0  0 77]
 [68 52 83  0]
 [92 84 64 86]]


### **Задание №6. Линейная алгебра:**

   а) Создайте два массива размером 3x3 и выполните их матричное умножение:


In [ ]:
# Ваш код
f = np.random.randint(0, 101, (3, 3))
s = np.random.randint(0, 101, (3, 3))
prod = np.dot(f, s)
print('Первый массив:\n',f)
print('Второй массив:\n',s)
print('Произведение:\n', prod)

Первый массив:
 [[94 54 13]
 [88 34 10]
 [37 91 82]]
Второй массив:
 [[93 56 15]
 [60 51 94]
 [61 76 56]]
Произведение:
 [[12775  9006  7214]
 [10834  7422  5076]
 [13903 12945 13701]]


   б) Найдите обратную матрицу для созданного двумерного массива 3x3:

In [ ]:
# Ваш код
inverse_matrix = np.linalg.inv(f)
print(inverse_matrix)

[[-0.0178175   0.03078689 -0.00092977]
 [ 0.06495133 -0.06856606 -0.00193545]
 [-0.06404053  0.06219996  0.01476253]]


## **Блок №2. Средний уровень**

### **Задание №1. Работа с многомерными массивами:**
   


а) Создайте трехмерный массив со случайными целыми числами и выполните транспонирование так, чтобы порядок осей стал обратным:

In [ ]:
# Ваш код
rand_int = np.random.randint(0, 101, size=(3, 4, 5))
transposed_array = np.transpose(rand_int, (2, 1, 0))

print("Исходный трехмерный массив:\n", rand_int)
print("Транспонированный массив с обратным порядком осей:\n", transposed_array)

Исходный трехмерный массив:
 [[[55 47 70 70 25]
  [70 20 66  2 44]
  [ 5 29 56 41  7]
  [ 9 83 25 25 58]]

 [[18 66 24 27 51]
  [19 34 29 77 38]
  [46 63 95 64 74]
  [10 30  2 57  0]]

 [[21 38 45  3 86]
  [21  2 41 76 53]
  [45 36 69 30 63]
  [89 18 85 83 14]]]
Транспонированный массив с обратным порядком осей:
 [[[55 18 21]
  [70 19 21]
  [ 5 46 45]
  [ 9 10 89]]

 [[47 66 38]
  [20 34  2]
  [29 63 36]
  [83 30 18]]

 [[70 24 45]
  [66 29 41]
  [56 95 69]
  [25  2 85]]

 [[70 27  3]
  [ 2 77 76]
  [41 64 30]
  [25 57 83]]

 [[25 51 86]
  [44 38 53]
  [ 7 74 63]
  [58  0 14]]]


   б) Измените форму массива из предыдущего пункта так, чтобы получился двумерный массив (подумайте, как сохранить данные без потерь):

In [ ]:
# Ваш код
reshaped_ints = np.reshape(rand_int, (10, 6))
print("Двумерный массив после изменения формы:\n", reshaped_ints)

Двумерный массив после изменения формы:
 [[55 47 70 70 25 70]
 [20 66  2 44  5 29]
 [56 41  7  9 83 25]
 [25 58 18 66 24 27]
 [51 19 34 29 77 38]
 [46 63 95 64 74 10]
 [30  2 57  0 21 38]
 [45  3 86 21  2 41]
 [76 53 45 36 69 30]
 [63 89 18 85 83 14]]


```python
# Входные данные:
[
  [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
  ],
  [
    [13, 14, 15, 16],
    [17, 18, 19, 20],
    [21, 22, 23, 24]
  ]
]
```


```python
# Выходные данные:
[
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16],
  [17, 18, 19, 20],
  [21, 22, 23, 24]
]
```


### **Задание №2. Маскирование и фильтрация:**
   а) Создайте массив со случайными целыми числами от -10 до 10. Затем, используя маскирование, замените все отрицательные числа на 0:


In [ ]:
# Ваш код
arr = np.random.randint(-10, 11, size=20)
print('Исходный:\n',arr)
arr[arr < 0] = 0
print('Измененный:\n', arr)

Исходный:
 [-4 -7 -8  3  7  3  5 -4 -4  4  9 -8  9  3  5 10  4 -4 -4 10]
Измененный:
 [ 0  0  0  3  7  3  5  0  0  4  9  0  9  3  5 10  4  0  0 10]


   б) Создайте двумерный массив и найдите значения, которые больше среднего значения по всему массиву, и замените их на 1:

In [ ]:
# Ваш код
rand = np.random.randint(0, 101, size=(4, 4))
print("Исходный:\n", rand)

mean_value = np.mean(random_array)
print("Среднее:\n", mean_value)

rand[random_array > mean_value] = 1
print("Получившийся:\n", rand)

Исходный:
 [[34 43 51 22]
 [94 64 37  2]
 [61 99 14 23]
 [90 71 78  9]]
Среднее:
 61.1875
Получившийся:
 [[ 1  1  1 22]
 [ 1 64 37  1]
 [ 1 99  1 23]
 [ 1  1  1  1]]


### **Задание №3. Агрегирование данных:**


   а) Создайте двумерный массив со случайными числами. Вычислите сумму, среднее, максимум и минимум по столбцам и строкам:


In [ ]:
# Ваш код
rand = np.random.randint(0, 101, size=(4, 4))
print("Исходный:\n", rand)
print('По столбцам \n Сумма:', np.sum(rand, axis=0), '\n Среднее:', np.mean(rand, axis=0), '\n Макс:', np.max(rand, axis=0),'\n Мин:', np.min(rand, axis=0))
print('По строкам \n Сумма:', np.sum(rand, axis=1), '\n Среднее:', np.mean(rand, axis=1), '\n Макс:', np.max(rand, axis=1),'\n Мин:', np.min(rand, axis=1))

Исходный:
 [[53 42 24 82]
 [28 30 52  9]
 [79 56 75 59]
 [61  2 62 99]]
По столбцам 
 Сумма: [221 130 213 249] 
 Среднее: [55.25 32.5  53.25 62.25] 
 Макс: [79 56 75 99] 
 Мин: [28  2 24  9]
По строкам 
 Сумма: [201 119 269 224] 
 Среднее: [50.25 29.75 67.25 56.  ] 
 Макс: [82 52 79 99] 
 Мин: [24  9 56  2]


   б) Сгенерируйте массив случайных чисел и найдите дисперсию и стандартное отклонение:

In [ ]:
# Ваш код
random_array = np.random.randint(0, 101, size=100)

var_val = np.var(random_array)
std_dev = np.std(random_array)


print("Исходный:\n",random_array)
print("Дисперсия:", var_val)
print("Стандартное отклонение:", std_dev)

Исходный:
 [ 10  35  56  97  60  31  80  95   5  44  38  88  50  23   0  67  46  37
   2   8  41   1  85   3  13  11  79  72  25  18  68  81  17 100  80  75
  96  65  90  57  26  26  44  35  89  81  90  79  80  94  64  22  97  27
  71  18  16  36  93  48  93  94  48  60  37  33  91  75  74  71  46  80
  46  50  35  42  90  62  62  91  15  67  57  66  13  52  81  92  75  79
  91  95  60  66  93  18  83   9  88  56]
Дисперсия: 857.7659000000001
Стандартное отклонение: 29.287640738031463


### **Задание №4. Использование функций для работы с матрицами:**

   а) Используйте функцию [`np.linalg.eig`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html#numpy.linalg.eig) для нахождения собственных значений и собственных векторов квадратной матрицы:

In [ ]:
# Ваш код
random_matrix = np.random.randint(0, 11, size=(3, 3))
eigenvalues, eigenvectors = np.linalg.eig(random_matrix)

print("Исходная матрица:\n", random_matrix)
print("Собственные значения:\n", eigenvalues)
print("Собственные векторы:\n", eigenvectors)

Исходная матрица:
 [[ 5  0  8]
 [ 7 10  4]
 [ 3  5  6]]
Собственные значения:
 [15.91566972+0.j         2.54216514+2.9354514j  2.54216514-2.9354514j]
Собственные векторы:
 [[ 0.37020331+0.j          0.74931116+0.j          0.74931116-0.j        ]
 [ 0.77961278+0.j         -0.45179881-0.32529772j -0.45179881+0.32529772j]
 [ 0.50512713+0.j         -0.23021039+0.27494581j -0.23021039-0.27494581j]]


   б) Решите систему линейных уравнений Ax = B, используя `np.linalg.solve`, где A и B — матрицы, заданные вами:

In [ ]:
# Ваш код
A = np.array([[3, 2, -1],
              [2, -2, 4],
              [-1, 0.5, -1]])

B = np.array([1, -2, 0])
x = np.linalg.solve(A, B)

print(x)

[ 1. -2. -2.]


### **Задание №5. Работа с датасетом:**

   а) Загрузите датасет [**fetch california housing**](https://www.kaggle.com/datasets/harrywang/housing):

In [ ]:
import numpy as np
from sklearn.datasets import fetch_california_housing

dataset = fetch_california_housing().data
dataset = np.asarray(dataset, np.float64)

б) Выведите первые 5 элементов датасета:

In [ ]:
# Ваш код
print(dataset[:5])

[[ 8.32520000e+00  4.10000000e+01  6.98412698e+00  1.02380952e+00
   3.22000000e+02  2.55555556e+00  3.78800000e+01 -1.22230000e+02]
 [ 8.30140000e+00  2.10000000e+01  6.23813708e+00  9.71880492e-01
   2.40100000e+03  2.10984183e+00  3.78600000e+01 -1.22220000e+02]
 [ 7.25740000e+00  5.20000000e+01  8.28813559e+00  1.07344633e+00
   4.96000000e+02  2.80225989e+00  3.78500000e+01 -1.22240000e+02]
 [ 5.64310000e+00  5.20000000e+01  5.81735160e+00  1.07305936e+00
   5.58000000e+02  2.54794521e+00  3.78500000e+01 -1.22250000e+02]
 [ 3.84620000e+00  5.20000000e+01  6.28185328e+00  1.08108108e+00
   5.65000000e+02  2.18146718e+00  3.78500000e+01 -1.22250000e+02]]


в) Выведите размерность датасета:

In [ ]:
# Ваш код
print("Размерность датасета:", dataset.shape)

Размерность датасета: (20640, 8)


г) Выведите общее количество элементов датасета:

In [ ]:
# Ваш код
print("Количество элементов:", dataset.size)

Количество элементов: 165120


д) Выведите тип данных элементов датасета:

In [ ]:
# Ваш код
print("Тип данных элементов массива:", dataset.dtype)

Тип данных элементов массива: float64


е) Выведите количество измерений (осей) датасета:

In [ ]:
# Ваш код
print("Количество измерений:", dataset.ndim)

Количество измерений: 2


ё) Выведите общее количество байт, занимаемых элементами датасета:

In [ ]:
# Ваш код
print("Общее количество байт:", dataset.nbytes)

Общее количество байт: 1320960


ж) Выведите размер одного элемента датасета в байтах:

In [ ]:
# Ваш код
print("Размер одного элемента в байтах:", dataset.itemsize)

Размер одного элемента в байтах: 8


 з) Выполните нормализацию данных в **столбцах**, приведя их к диапазону от 0 до 1, написав для этого отдельную функцию, реализующую алгоритм MinMaxScaler:

Алгоритм MinMaxScaler является методом масштабирования, который линейно преобразует данные так, чтобы они помещались в заданный диапазон, обычно между 0 и 1. Это достигается путем вычитания минимального значения признака из каждого значения, а затем деления разности на размах значений (максимальное значение минус минимальное значение). Преобразование можно выразить следующей формулой:

$X_{\text{scaled}} = \frac{X - X_{\min}}{X_{\max} - X_{\min}}$

Где:
- $X$ — исходное значение признака,
- $X_{\min}$ — минимальное значение этого признака в наборе данных,
- $X_{\max}$ — максимальное значение признака в наборе данных,
- $X_{\text{scaled}}$ — масштабированное значение признака.

Если требуется масштабировать данные в другой диапазон, например, $[a, b]$, то формула модифицируется:

$X_{\text{scaled}} = a + \frac{(X - X_{\min}) \times (b - a)}{X_{\max} - X_{\min}}$

In [ ]:
# Ваш код
def min_max_scaler(X, feature_range=(0, 1)):
    a, b = feature_range
    Xmin = np.min(X, axis=0)
    Xmax = np.max(X, axis=0)

    X_scaled = a + (X - Xmin) * (b - a) / (Xmax - Xmin)
    return X_scaled

data_scaled = min_max_scaler(dataset)
print("Массив данных после нормализации:\n", data_scaled)

Массив данных после нормализации:
 [[0.53966842 0.78431373 0.0435123  ... 0.00149943 0.5674814  0.21115538]
 [0.53802706 0.39215686 0.03822395 ... 0.00114074 0.565356   0.21215139]
 [0.46602805 1.         0.05275646 ... 0.00169796 0.5642933  0.21015936]
 ...
 [0.08276438 0.31372549 0.03090386 ... 0.0013144  0.73219979 0.31175299]
 [0.09429525 0.33333333 0.03178269 ... 0.0011515  0.73219979 0.30179283]
 [0.13025338 0.29411765 0.03125246 ... 0.00154886 0.72582359 0.30976096]]


   и) Используйте логическую индексацию для фильтрации данных по заданному условию (например, выберите все строки, где значение в определённом столбце превышает среднее значение этого столбца и выведите их значение):

In [ ]:
# Ваш код
def filter_by_column_mean(X, column_index):
    column_mean = np.mean(X[:, column_index])
    # выбираем строки, где значение в указанном столбце превышает среднее
    filtered_rows = X[X[:, column_index] > column_mean]
    return filtered_rows

filtered_data = filter_by_column_mean(dataset, column_index=3)
print("Отфильтрованные строки:\n", filtered_data)

Отфильтрованные строки:
 [[   4.0368       52.            4.76165803 ...    2.13989637
    37.85       -122.25      ]
 [   2.0804       42.            4.29411765 ...    2.02689076
    37.84       -122.26      ]
 [   2.6736       52.            4.         ...    1.98275862
    37.84       -122.26      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]


### **Задание №6. Работа с многомерными данными:**

Создайте двумерный массив и выполните "сглаживание" данных, заменив каждый элемент средним значением его и соседних элементов (по сторонам и по диагонали):



```
Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Smoothed Array:
[[3 3 4]
 [4 5 5]
 [6 6 7]]
```



In [ ]:
# Ваш код
def smooth_array(arr):
    # Создаем массив для хранения сглаженных значений
    smoothed_arr = np.zeros_like(arr, dtype=float)

    # Размеры массива
    rows, cols = arr.shape

    # Проходим по каждому элементу массива
    for i in range(rows):
        for j in range(cols):
            # Список для хранения значений соседей
            neighbors = []

            # Добавляем текущий элемент
            neighbors.append(arr[i, j])

            # Добавляем соседей сверху
            if i > 0:
                neighbors.append(arr[i-1, j])
                if j > 0:
                    neighbors.append(arr[i-1, j-1])
                if j < cols - 1:
                    neighbors.append(arr[i-1, j+1])

            # Добавляем соседей снизу
            if i < rows - 1:
                neighbors.append(arr[i+1, j])
                if j > 0:
                    neighbors.append(arr[i+1, j-1])
                if j < cols - 1:
                    neighbors.append(arr[i+1, j+1])

            # Добавляем соседей слева и справа
            if j > 0:
                neighbors.append(arr[i, j-1])
            if j < cols - 1:
                neighbors.append(arr[i, j+1])

            # Вычисляем среднее значение и округляем
            smoothed_arr[i, j] = np.floor(np.mean(neighbors))


    # Преобразуем массив в целые числа
    smoothed_arr = smoothed_arr.astype(int)

    return smoothed_arr

original_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Исходный массив:\n", original_array)

smoothed_array = smooth_array(original_array)
print("Сглаженный массив:\n", smoothed_array)

Исходный массив:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Сглаженный массив:
 [[3 3 4]
 [4 5 5]
 [6 6 7]]
